# Generated by Django 4.0.4 on 2022-05-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación/rechazo'),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_desembolso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de desembolso'),
        ),
    ]
