# Generated by Django 4.0.4 on 2022-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_credito_fecha_alta_credito_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado'), (4, 'Desembolsado')], default=1),
        ),
    ]
