# Generated by Django 4.0.4 on 2022-05-13 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_alter_credito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 5, 13, 2, 32, 20, 679503, tzinfo=utc)),
        ),
    ]
