# Generated by Django 4.0.4 on 2022-05-14 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_cuotero_unique_together'),
        ('credito', '0004_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 21, 5, 22, 301405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='credito',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='base.vendedor', verbose_name='Oficial'),
        ),
    ]
