# Generated by Django 4.0.4 on 2022-05-14 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0005_alter_credito_fecha_alta_alter_credito_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 21, 18, 24, 625163, tzinfo=utc)),
        ),
    ]
