# Generated by Django 4.0.4 on 2022-05-15 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0007_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='numero',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Número solicitud'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 21, 35, 6, 39342, tzinfo=utc)),
        ),
    ]
