# Generated by Django 4.0.4 on 2022-05-15 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0008_credito_numero_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 22, 8, 15, 431742, tzinfo=utc)),
        ),
    ]
