# Generated by Django 4.0.4 on 2022-06-01 00:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0009_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 6, 1, 0, 36, 19, 696982, tzinfo=utc)),
        ),
    ]
