# Generated by Django 4.0.4 on 2022-06-10 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0010_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='saldo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 6, 10, 18, 8, 8, 910935, tzinfo=utc)),
        ),
    ]
