# Generated by Django 4.0.4 on 2022-06-12 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0013_alter_credito_fecha_alta_alter_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 1, 30, 8, 130540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='saldo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
