# Generated by Django 4.0.4 on 2022-06-15 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0015_alter_credito_fecha_alta_alter_cuota_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 14, 18, 32, 835263, tzinfo=utc)),
        ),
    ]
