# Generated by Django 4.0.4 on 2022-07-07 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0016_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 1, 30, 20, 514410, tzinfo=utc)),
        ),
    ]
