# Generated by Django 4.0.4 on 2022-08-19 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0017_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 8, 19, 15, 45, 34, 820248, tzinfo=utc)),
        ),
    ]
