# Generated by Django 4.0.4 on 2022-08-22 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0020_alter_credito_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 15, 38, 29, 292308, tzinfo=utc)),
        ),
    ]
