# Generated by Django 4.0.4 on 2022-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(blank=True, max_length=16, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('apellido',),
            },
        ),
        migrations.CreateModel(
            name='ComisionMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('mora_por_dia', models.PositiveIntegerField()),
                ('comision', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Comisión y Mora',
                'verbose_name_plural': 'Comisiones y Moras',
                'ordering': ('monto',),
            },
        ),
        migrations.CreateModel(
            name='Cuotero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('cuotas', models.PositiveIntegerField()),
                ('tipo_plazo', models.IntegerField(choices=[(8, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual')])),
                ('pagare', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Cuotero',
                'verbose_name_plural': 'Cuotas',
                'ordering': ('monto',),
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ('apellido',),
            },
        ),
    ]
