# Generated by Django 4.0.4 on 2022-04-27 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuotero',
            name='pagare',
            field=models.PositiveIntegerField(verbose_name='Pagaré'),
        ),
        migrations.AlterField(
            model_name='cuotero',
            name='tipo_plazo',
            field=models.IntegerField(choices=[(8, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual')], verbose_name='Tipo de plazo'),
        ),
    ]
