# Generated by Django 4.0.4 on 2022-05-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tipodocumento_usuario_cliente_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ('nombre',), 'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tipo_documento', 'ci')},
        ),
    ]
