# Generated by Django 4.0.4 on 2022-05-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cliente_options_alter_vendedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotero',
            name='tipo_plazo',
            field=models.IntegerField(choices=[(7, 'Semanal'), (14, 'Quincenal'), (30, 'Mensual')], verbose_name='Tipo de plazo'),
        ),
    ]
