# Generated by Django 4.0.4 on 2022-05-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_cuotero_options_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuotero',
            unique_together={('monto', 'cuotas', 'tipo_plazo')},
        ),
    ]
