# Generated by Django 4.0.4 on 2022-05-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_cuotero_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuotero',
            unique_together={('monto', 'cuotas', 'tipo_plazo', 'pagare')},
        ),
    ]
