# Generated by Django 4.0.4 on 2022-08-19 15:25
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cuotero_unique_together'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
