# Generated by Django 4.0.4 on 2022-08-19 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_postgis_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ubicacion',
            field=django.contrib.gis.db.models.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
