# Generated by Django 4.0.4 on 2022-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cliente_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitud_ubicacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud_ubicacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
