# Generated by Django 4.0.4 on 2022-08-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_cliente_latitud_ubicacion_cliente_longitud_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ubicacion',
        ),
    ]
