# Generated by Django 4.0.4 on 2022-04-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=128)),
                ('tipo', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')])),
                ('monto', models.PositiveIntegerField()),
                ('saldo', models.IntegerField()),
                ('pago_cuota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_caja', to='credito.pago')),
            ],
        ),
    ]
