# Generated by Django 4.0.4 on 2022-05-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_conceptomovimiento_movimientocaja_concepto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptomovimiento',
            options={'ordering': ('nombre',), 'verbose_name': 'Concepto de movimiento', 'verbose_name_plural': 'Conceptos de movimientos'},
        ),
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={'ordering': ('fecha',), 'verbose_name': 'Movimiento de caja', 'verbose_name_plural': 'Movimientos de caja'},
        ),
    ]
