# Generated by Django 4.0.4 on 2022-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_conceptomovimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
